# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lysandre/Documents/tests/JLinkage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lysandre/Documents/tests/JLinkage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lysandre/Documents/tests/JLinkage/CMakeFiles /home/lysandre/Documents/tests/JLinkage//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lysandre/Documents/tests/JLinkage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jlk

# Build rule for target.
jlk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jlk
.PHONY : jlk

# fast build rule for target.
jlk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/build
.PHONY : jlk/fast

JLinkage.o: JLinkage.cpp.o
.PHONY : JLinkage.o

# target to build an object file
JLinkage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/JLinkage.cpp.o
.PHONY : JLinkage.cpp.o

JLinkage.i: JLinkage.cpp.i
.PHONY : JLinkage.i

# target to preprocess a source file
JLinkage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/JLinkage.cpp.i
.PHONY : JLinkage.cpp.i

JLinkage.s: JLinkage.cpp.s
.PHONY : JLinkage.s

# target to generate assembly for a file
JLinkage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/JLinkage.cpp.s
.PHONY : JLinkage.cpp.s

cluster.o: cluster.cpp.o
.PHONY : cluster.o

# target to build an object file
cluster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/cluster.cpp.o
.PHONY : cluster.cpp.o

cluster.i: cluster.cpp.i
.PHONY : cluster.i

# target to preprocess a source file
cluster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/cluster.cpp.i
.PHONY : cluster.cpp.i

cluster.s: cluster.cpp.s
.PHONY : cluster.s

# target to generate assembly for a file
cluster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/cluster.cpp.s
.PHONY : cluster.cpp.s

line.o: line.cpp.o
.PHONY : line.o

# target to build an object file
line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/line.cpp.o
.PHONY : line.cpp.o

line.i: line.cpp.i
.PHONY : line.i

# target to preprocess a source file
line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/line.cpp.i
.PHONY : line.cpp.i

line.s: line.cpp.s
.PHONY : line.s

# target to generate assembly for a file
line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/line.cpp.s
.PHONY : line.cpp.s

model.o: model.cpp.o
.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i
.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s
.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/model.cpp.s
.PHONY : model.cpp.s

point.o: point.cpp.o
.PHONY : point.o

# target to build an object file
point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/point.cpp.o
.PHONY : point.cpp.o

point.i: point.cpp.i
.PHONY : point.i

# target to preprocess a source file
point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/point.cpp.i
.PHONY : point.cpp.i

point.s: point.cpp.s
.PHONY : point.s

# target to generate assembly for a file
point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/point.cpp.s
.PHONY : point.cpp.s

window.o: window.cpp.o
.PHONY : window.o

# target to build an object file
window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/window.cpp.o
.PHONY : window.cpp.o

window.i: window.cpp.i
.PHONY : window.i

# target to preprocess a source file
window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/window.cpp.i
.PHONY : window.cpp.i

window.s: window.cpp.s
.PHONY : window.s

# target to generate assembly for a file
window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jlk.dir/build.make CMakeFiles/jlk.dir/window.cpp.s
.PHONY : window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... jlk"
	@echo "... JLinkage.o"
	@echo "... JLinkage.i"
	@echo "... JLinkage.s"
	@echo "... cluster.o"
	@echo "... cluster.i"
	@echo "... cluster.s"
	@echo "... line.o"
	@echo "... line.i"
	@echo "... line.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

